### ISSUE TITLE
Possible to add the "Print" section to Notification plugin?

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/http-notification#2]
I can see a scenario where I would like to store the response from the HTTP Notification event for future analysis, in the event an issue occurred.  Would be nice to have the "Print" section available as it is for the Job Step.

"Print Response" option could add to the execution log, and "Print Response to File" could function as described.  Would like to make sure execution variables are available for use in this Notification plugin as well (exec id, job name, project name, etc)

**Comment by miguelantonio** [comment]
Hi @fellenberger I'm adding this
